//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
#![allow(unused_imports)]
pub use super::comments::Entity as Comments;
pub use super::likes::Entity as Likes;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
